CREATE TABLE IF NOT EXISTS players (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(190) NOT NULL,
    level TINYINT UNSIGNED NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uniq_players_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS league_participants (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(120) NOT NULL,
    team_name VARCHAR(120) NOT NULL,
    mobile VARCHAR(20) NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uniq_league_participants_mobile (mobile)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS league_matches (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    stage VARCHAR(50) NOT NULL DEFAULT 'Group Stage',
    group_name VARCHAR(20) NULL,
    match_date DATE NOT NULL,
    local_time TIME NULL,
    home_team VARCHAR(120) NOT NULL,
    away_team VARCHAR(120) NOT NULL,
    venue VARCHAR(190) NULL,
    venue_city VARCHAR(120) NULL,
    notes VARCHAR(255) NULL,
    result ENUM('home', 'away', 'draw') NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_league_matches_match_date (match_date),
    KEY idx_league_matches_stage_group (stage, group_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS league_votes (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    participant_id INT UNSIGNED NOT NULL,
    match_id INT UNSIGNED NOT NULL,
    prediction ENUM('home', 'away', 'draw') NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uniq_league_votes_participant_match (participant_id, match_id),
    KEY idx_league_votes_match_id (match_id),
    CONSTRAINT fk_league_votes_participant FOREIGN KEY (participant_id) REFERENCES league_participants (id) ON DELETE CASCADE,
    CONSTRAINT fk_league_votes_match FOREIGN KEY (match_id) REFERENCES league_matches (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DELETE FROM league_matches;

INSERT INTO league_matches (stage, group_name, match_date, local_time, home_team, away_team, venue, venue_city, notes, result, created_at, updated_at) VALUES
('Group Stage', 'Group A', '2026-06-11', '19:00:00', 'Mexico', 'South Africa', 'Estadio Azteca', 'Mexico City', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group A', '2026-06-11', '20:00:00', 'South Korea', 'Czechia', 'Estadio Akron', 'Guadalajara', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group A', '2026-06-18', '12:00:00', 'Czechia', 'South Africa', 'Mercedes-Benz Stadium', 'Atlanta', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group A', '2026-06-18', '19:00:00', 'Mexico', 'South Korea', 'Estadio Akron', 'Guadalajara', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group A', '2026-06-24', '16:30:00', 'South Africa', 'South Korea', 'Estadio Akron', 'Guadalajara', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group A', '2026-06-24', '16:30:00', 'Czechia', 'Mexico', 'Estadio Azteca', 'Mexico City', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group B', '2026-06-12', '15:00:00', 'Canada', 'Bosnia & Herzegovina', 'BMO Field', 'Toronto', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group B', '2026-06-13', '12:00:00', 'Qatar', 'Switzerland', 'Levi''s Stadium', 'San Francisco', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group B', '2026-06-18', '12:00:00', 'Switzerland', 'Bosnia & Herzegovina', 'SoFi Stadium', 'Los Angeles', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group B', '2026-06-18', '15:00:00', 'Canada', 'Qatar', 'BC Place', 'Vancouver', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group B', '2026-06-24', '12:00:00', 'Switzerland', 'Canada', 'BC Place', 'Vancouver', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group B', '2026-06-24', '12:00:00', 'Bosnia & Herzegovina', 'Qatar', 'Lumen Field', 'Seattle', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group C', '2026-06-13', '21:00:00', 'Haiti', 'Scotland', 'Gillette Stadium', 'Boston', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group C', '2026-06-13', '18:00:00', 'Brazil', 'Morocco', 'MetLife Stadium', 'New York/New Jersey', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group C', '2026-06-19', '18:00:00', 'Scotland', 'Morocco', 'Gillette Stadium', 'Boston', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group C', '2026-06-19', '19:00:00', 'Brazil', 'Haiti', 'Lincoln Financial Field', 'Philadelphia', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group C', '2026-06-24', '21:00:00', 'Scotland', 'Brazil', 'Hard Rock Stadium', 'Miami', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group C', '2026-06-24', '21:00:00', 'Morocco', 'Haiti', 'Mercedes-Benz Stadium', 'Atlanta', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group D', '2026-06-12', '18:00:00', 'USA', 'Paraguay', 'SoFi Stadium', 'Los Angeles', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group D', '2026-06-13', '21:00:00', 'Australia', 'Turkiye', 'BC Place', 'Vancouver', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group D', '2026-06-19', '20:00:00', 'Turkiye', 'Paraguay', 'Levi''s Stadium', 'San Francisco', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group D', '2026-06-19', '12:00:00', 'USA', 'Australia', 'Lumen Field', 'Seattle', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group D', '2026-06-25', '15:00:00', 'Turkiye', 'USA', 'SoFi Stadium', 'Los Angeles', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group D', '2026-06-25', '15:00:00', 'Paraguay', 'Australia', 'Levi''s Stadium', 'San Francisco', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group E', '2026-06-14', '19:00:00', 'Ivory Coast', 'Ecuador', 'Lincoln Financial Field', 'Philadelphia', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group E', '2026-06-14', '12:00:00', 'Germany', 'Curacao', 'NRG Stadium', 'Houston', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group E', '2026-06-20', '16:00:00', 'Germany', 'Ivory Coast', 'BMO Field', 'Toronto', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group E', '2026-06-20', '19:00:00', 'Ecuador', 'Curacao', 'Arrowhead Stadium', 'Kansas City', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group E', '2026-06-25', '20:30:00', 'Curacao', 'Ivory Coast', 'Lincoln Financial Field', 'Philadelphia', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group E', '2026-06-25', '20:30:00', 'Ecuador', 'Germany', 'MetLife Stadium', 'New York/New Jersey', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group F', '2026-06-14', '15:00:00', 'Netherlands', 'Japan', 'AT&T Stadium', 'Dallas', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group F', '2026-06-14', '20:00:00', 'Sweden', 'Tunisia', 'Estadio BBVA', 'Monterrey', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group F', '2026-06-20', '12:00:00', 'Netherlands', 'Sweden', 'NRG Stadium', 'Houston', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group F', '2026-06-20', '22:00:00', 'Tunisia', 'Japan', 'Estadio BBVA', 'Monterrey', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group F', '2026-06-25', '15:00:00', 'Tunisia', 'Netherlands', 'Arrowhead Stadium', 'Kansas City', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group F', '2026-06-25', '15:00:00', 'Japan', 'Sweden', 'AT&T Stadium', 'Dallas', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group G', '2026-06-15', '18:00:00', 'Iran', 'New Zealand', 'SoFi Stadium', 'Los Angeles', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group G', '2026-06-15', '12:00:00', 'Belgium', 'Egypt', 'Lumen Field', 'Seattle', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group G', '2026-06-21', '12:00:00', 'Belgium', 'Iran', 'SoFi Stadium', 'Los Angeles', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group G', '2026-06-21', '18:00:00', 'New Zealand', 'Egypt', 'BC Place', 'Vancouver', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group G', '2026-06-26', '20:00:00', 'Egypt', 'Iran', 'Lumen Field', 'Seattle', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group G', '2026-06-26', '20:00:00', 'New Zealand', 'Belgium', 'BC Place', 'Vancouver', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group H', '2026-06-15', '18:00:00', 'Saudi Arabia', 'Uruguay', 'Hard Rock Stadium', 'Miami', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group H', '2026-06-15', '12:00:00', 'Spain', 'Cabo Verde', 'Mercedes-Benz Stadium', 'Atlanta', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group H', '2026-06-21', '12:00:00', 'Spain', 'Saudi Arabia', 'Mercedes-Benz Stadium', 'Atlanta', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group H', '2026-06-21', '18:00:00', 'Uruguay', 'Cabo Verde', 'Hard Rock Stadium', 'Miami', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group H', '2026-06-26', '13:00:00', 'Cabo Verde', 'Saudi Arabia', 'NRG Stadium', 'Houston', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group H', '2026-06-26', '12:00:00', 'Uruguay', 'Spain', 'Estadio Akron', 'Guadalajara', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group I', '2026-06-16', '15:00:00', 'France', 'Senegal', 'MetLife Stadium', 'New York/New Jersey', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group I', '2026-06-16', '18:00:00', 'Iraq', 'Norway', 'Gillette Stadium', 'Boston', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group I', '2026-06-22', '20:00:00', 'Norway', 'Senegal', 'MetLife Stadium', 'New York/New Jersey', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group I', '2026-06-22', '17:00:00', 'France', 'Iraq', 'Lincoln Financial Field', 'Philadelphia', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group I', '2026-06-26', '16:30:00', 'Norway', 'France', 'Gillette Stadium', 'Boston', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group I', '2026-06-26', '16:30:00', 'Senegal', 'Iraq', 'BMO Field', 'Toronto', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group J', '2026-06-16', '20:00:00', 'Argentina', 'Algeria', 'Arrowhead Stadium', 'Kansas City', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group J', '2026-06-16', '21:00:00', 'Austria', 'Jordan', 'Levi''s Stadium', 'San Francisco', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group J', '2026-06-22', '12:00:00', 'Argentina', 'Austria', 'AT&T Stadium', 'Dallas', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group J', '2026-06-22', '20:00:00', 'Jordan', 'Algeria', 'Levi''s Stadium', 'San Francisco', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group J', '2026-06-27', '21:00:00', 'Algeria', 'Austria', 'Arrowhead Stadium', 'Kansas City', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group J', '2026-06-27', '21:00:00', 'Jordan', 'Argentina', 'AT&T Stadium', 'Dallas', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group K', '2026-06-17', '12:00:00', 'Portugal', 'Congo DR', 'NRG Stadium', 'Houston', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group K', '2026-06-17', '20:00:00', 'Uzbekistan', 'Colombia', 'Estadio Azteca', 'Mexico City', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group K', '2026-06-23', '15:00:00', 'Portugal', 'Uzbekistan', 'NRG Stadium', 'Houston', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group K', '2026-06-23', '20:00:00', 'Colombia', 'Congo DR', 'Estadio Akron', 'Guadalajara', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group K', '2026-06-27', '18:30:00', 'Colombia', 'Portugal', 'Hard Rock Stadium', 'Miami', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group K', '2026-06-27', '18:30:00', 'Congo DR', 'Uzbekistan', 'Mercedes-Benz Stadium', 'Atlanta', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group L', '2026-06-17', '19:00:00', 'Ghana', 'Panama', 'BMO Field', 'Toronto', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group L', '2026-06-17', '15:00:00', 'England', 'Croatia', 'AT&T Stadium', 'Dallas', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group L', '2026-06-23', '16:00:00', 'England', 'Ghana', 'Gillette Stadium', 'Boston', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group L', '2026-06-23', '19:00:00', 'Panama', 'Croatia', 'BMO Field', 'Toronto', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group L', '2026-06-27', '16:00:00', 'Panama', 'England', 'MetLife Stadium', 'New York/New Jersey', NULL, NULL, NOW(), NOW()),
('Group Stage', 'Group L', '2026-06-27', '16:00:00', 'Croatia', 'Ghana', 'Lincoln Financial Field', 'Philadelphia', NULL, NULL, NOW(), NOW());
